config/routes.rb
GeoPrice::Application.routes.draw do
  resources :dummy_tables

  resources :stores

  resources :stocks

  resources :attributes

  resources :productcategories

  resources :categories

  resources :manufacturers

  resources :products

  resources :wishlistitems

  resources :wishlists

  resources :roles

  resources :credentials

  resources :users

end

app/models/attribute.rb
class Attribute < ActiveRecord::Base
  attr_accessible :AttributeDescription, :AttributeID, :AttributeName, :AttributeValue, :AttributeValueUnit, :ProductID
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :CategoryID, :CategoryName, :SubCategory
end

app/models/credential.rb
class Credential < ActiveRecord::Base
  attr_accessible :Password, :RoleID, :UserID
end

app/models/dummy_table.rb
class DummyTable < ActiveRecord::Base
  attr_accessible :isStudent, :lastName, :name
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  attr_accessible :Address, :City, :Email, :Fax, :ManufacturerID, :Name, :Phone, :PostCode
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :Description, :ManufacturerID, :Name, :ProductID, :Type
end

app/models/productcategory.rb
class Productcategory < ActiveRecord::Base
  attr_accessible :CategoryID, :ProductID
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :RoleID, :RoleName
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  attr_accessible :Price, :ProductID, :Quantity, :StoreID
end

app/models/store.rb
class Store < ActiveRecord::Base
  attr_accessible :Address, :City, :Email, :Name, :Phone, :PostCode, :StoreID, :StoreType
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :Address, :City, :Email, :FirstName, :LastName, :Phone, :Postcode, :UserID, :Username
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  attr_accessible :LastName, :LastUpdated, :ListID, :UserID, :ValidFrom, :ValidTo
end

app/models/wishlistitem.rb
class Wishlistitem < ActiveRecord::Base
  attr_accessible :DesiredPrice, :ListID, :PriceVariance, :ProductID, :Quantity, :StoreType
end

app/controllers/attributes_controller.rb
class AttributesController < ApplicationController
  # GET /attributes
  # GET /attributes.json
  def index
    @attributes = Attribute.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attributes }
    end
  end

  # GET /attributes/1
  # GET /attributes/1.json
  def show
    @attribute = Attribute.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attribute }
    end
  end

  # GET /attributes/new
  # GET /attributes/new.json
  def new
    @attribute = Attribute.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attribute }
    end
  end

  # GET /attributes/1/edit
  def edit
    @attribute = Attribute.find(params[:id])
  end

  # POST /attributes
  # POST /attributes.json
  def create
    @attribute = Attribute.new(params[:attribute])

    respond_to do |format|
      if @attribute.save
        format.html { redirect_to @attribute, notice: 'Attribute was successfully created.' }
        format.json { render json: @attribute, status: :created, location: @attribute }
      else
        format.html { render action: "new" }
        format.json { render json: @attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attributes/1
  # PUT /attributes/1.json
  def update
    @attribute = Attribute.find(params[:id])

    respond_to do |format|
      if @attribute.update_attributes(params[:attribute])
        format.html { redirect_to @attribute, notice: 'Attribute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attributes/1
  # DELETE /attributes/1.json
  def destroy
    @attribute = Attribute.find(params[:id])
    @attribute.destroy

    respond_to do |format|
      format.html { redirect_to attributes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attributes_helper.rb
module AttributesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/attributes/_form.html.erb
<%= form_for(@attribute) do |f| %>
  <% if @attribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attribute.errors.count, "error") %> prohibited this attribute from being saved:</h2>

      <ul>
      <% @attribute.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :AttributeID %><br />
    <%= f.number_field :AttributeID %>
  </div>
  <div class="field">
    <%= f.label :ProductID %><br />
    <%= f.number_field :ProductID %>
  </div>
  <div class="field">
    <%= f.label :AttributeName %><br />
    <%= f.text_field :AttributeName %>
  </div>
  <div class="field">
    <%= f.label :AttributeDescription %><br />
    <%= f.text_field :AttributeDescription %>
  </div>
  <div class="field">
    <%= f.label :AttributeValue %><br />
    <%= f.text_field :AttributeValue %>
  </div>
  <div class="field">
    <%= f.label :AttributeValueUnit %><br />
    <%= f.text_field :AttributeValueUnit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attributes/edit.html.erb
<h1>Editing attribute</h1>

<%= render 'form' %>

<%= link_to 'Show', @attribute %> |
<%= link_to 'Back', attributes_path %>

app/views/attributes/index.html.erb
<h1>Listing attributes</h1>

<table>
  <tr>
    <th>Attributeid</th>
    <th>Productid</th>
    <th>Attributename</th>
    <th>Attributedescription</th>
    <th>Attributevalue</th>
    <th>Attributevalueunit</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attributes.each do |attribute| %>
  <tr>
    <td><%= attribute.AttributeID %></td>
    <td><%= attribute.ProductID %></td>
    <td><%= attribute.AttributeName %></td>
    <td><%= attribute.AttributeDescription %></td>
    <td><%= attribute.AttributeValue %></td>
    <td><%= attribute.AttributeValueUnit %></td>
    <td><%= link_to 'Show', attribute %></td>
    <td><%= link_to 'Edit', edit_attribute_path(attribute) %></td>
    <td><%= link_to 'Destroy', attribute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attribute', new_attribute_path %>

app/views/attributes/new.html.erb
<h1>New attribute</h1>

<%= render 'form' %>

<%= link_to 'Back', attributes_path %>

app/views/attributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Attributeid:</b>
  <%= @attribute.AttributeID %>
</p>

<p>
  <b>Productid:</b>
  <%= @attribute.ProductID %>
</p>

<p>
  <b>Attributename:</b>
  <%= @attribute.AttributeName %>
</p>

<p>
  <b>Attributedescription:</b>
  <%= @attribute.AttributeDescription %>
</p>

<p>
  <b>Attributevalue:</b>
  <%= @attribute.AttributeValue %>
</p>

<p>
  <b>Attributevalueunit:</b>
  <%= @attribute.AttributeValueUnit %>
</p>


<%= link_to 'Edit', edit_attribute_path(@attribute) %> |
<%= link_to 'Back', attributes_path %>